shoulda-matchers.gemspec

Give credit where credit is due.

Add Elliot Winkler to authors

---

spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Here, we are basically testing the logic that generates a next value for
a scope attribute, in the case that that attribute is a Time object
instead of a DateTime object.

Uniqueness: Add missing tests for scopes w/ datetime + Time

---

NEWS.md
lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/support/unit/helpers/active_record_versions.rb
spec/support/unit/helpers/database_helpers.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Uniqueness: Support PG array columns for scopes

---

README.md

* Move thanks to contributors to the top
* Remove credits section
* Introduce new "About thoughtbot" section.

Add "About thoughtbot" section to readme

---

NEWS.md
lib/shoulda/matchers/active_model/allow_value_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/even_number_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/numeric_type_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/odd_number_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/only_integer_matcher.rb
lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb
spec/unit/shoulda/matchers/active_model/numericality_matchers/comparison_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/numericality_matchers/even_number_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/numericality_matchers/odd_number_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/numericality_matchers/only_integer_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_numericality_of_matcher_spec.rb

WIP: Fix numericality matcher not to raise CouldNotSetAttributeError

---

lib/shoulda/matchers/active_model/allow_value_matcher.rb

English fix

---

lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb

Fixes https://github.com/thoughtbot/shoulda-matchers/issues/1001

Replace Fixnum with Integer

---

.travis.yml

Reverts thoughtbot/shoulda-matchers#1047

Revert "Allow failure of Rails 5.0 builds during v4.0 development"

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb

The name of FactoryGirl was changed to FactoryBot (making all of as using it really "happy" :angry:), so it should be updated it in the documentation.

Change FactoryGirl by FactoryBot

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_absence_of_matcher_spec.rb

Reverts thoughtbot/shoulda-matchers#1109
Reason: Intermittent test

Revert "Handle uuid columns in validate_absence_of"

---

.travis.yml

Add Ruby 2.5.1 builds to TravisCI

Add TravisCI Ruby 2.5.1 builds

---

.travis.yml
gemfiles/4.0.0.gemfile.lock
gemfiles/4.0.1.gemfile.lock
gemfiles/4.1.gemfile.lock
gemfiles/4.2.gemfile.lock

c.f. https://github.com/thoughtbot/shoulda-matchers/issues/1166#issuecomment-455235574

Fixed CI on v-3-1-stable branch

---

MIT-LICENSE
README.md

Happy new year! :tada: :tada: :tada:

Update license year

---

spec/support/tests/command_runner.rb

Fixes #1287 - an issue that appears to involve the child process blocking on writing output and the parent waiting for the child to finish.
In spec helpers command runner, read from the stdout/stderr pipe in a separate thread while waiting for the spawned process to finish.
As the affected code is a spec helper, it does not seem appropriate to add a spec for this behaviour. Here is a minimal example to showcase the fix:
```ruby
require './spec/support/tests/command_runner'
n = 65_536
runner = Tests::CommandRunner.new('ruby', '-e', %('print(("a" * #{n}) + ".")'))
runner.run_successfully = true
runner.run_quickly = true
runner.call
puts "actual length: #{runner.output.length}, expected: #{n+1}"
```

Read output while wating for spec command runner

---

CHANGELOG.md
README.md

* Rename from NEWS to CHANGELOG to match community convention
* Add dates to all releases
* Ensure that all pull requests / issues are linked and simplify those
links
[ci skip]

Revamp the changelog

---

lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
lib/shoulda/matchers/active_model/validate_length_of_matcher.rb
lib/shoulda/matchers/active_model/validation_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_length_of_matcher_spec.rb

This is an updated version of #725.
Closes #725.

Add the qualifier allow_blank to validate_length_of

---

custom_plan.rb

More info here: <https://github.com/burke/zeus/issues/674>

Fix Zeus so that it works with Pry 0.13.0+

---

lib/shoulda/matchers.rb
lib/shoulda/matchers/action_controller.rb
lib/shoulda/matchers/active_model.rb
lib/shoulda/matchers/active_model/allow_value_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers.rb
lib/shoulda/matchers/active_model/validation_matcher.rb
lib/shoulda/matchers/active_record.rb
lib/shoulda/matchers/active_record/association_matchers.rb
lib/shoulda/matchers/active_record/uniqueness.rb
lib/shoulda/matchers/doublespeak.rb
lib/shoulda/matchers/independent.rb
lib/shoulda/matchers/independent/delegate_method_matcher.rb
lib/shoulda/matchers/integrations.rb
lib/shoulda/matchers/integrations/test_frameworks.rb
lib/shoulda/matchers/util.rb

This PR reverts the commit ce78101362d8826d0bfaf4e7935aa0643f3e4c53.
Closes #1333  #1332 #1331.

Revert "Use autoloading instead of requiring all files up front"

---

CHANGELOG.md

[ci skip] fix typo in changelog

---

index.html

This PR update the List of matchers in index.html to be equal to the list in README.md

Update list of matchers in index.html [ci skip]

---

.github/workflows/rubocop.yml

feat: Add github action for linting rubocop

---

CHANGELOG.md

Bring CHANGELOG up to date

---

.github/workflows/ci.yml

Update ruby versions used in CI

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_absence_of_matcher_spec.rb

Support enum attributes on validate_absence_of

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

* Fix the undefined method error for non rails project due to the use of many? - method from ActiveSupport. ([#1459])
[#1459]: https://github.com/thoughtbot/shoulda-matchers/pull/1459
* Add array option support for have db column matcher. ([#1465])
* Add enum attributes support for validate_absence_of matcher. ([#1464])
[#1464]: https://github.com/thoughtbot/shoulda-matchers/pull/1464
[#1465]: https://github.com/thoughtbot/shoulda-matchers/pull/1465

Bump version to 5.1.0

---

lib/shoulda/matchers/active_model/validate_length_of_matcher.rb

Small UI fix for [this page](https://matchers.shoulda.io/docs/v5.1.0/Shoulda/Matchers/ActiveModel.html)

Fix documentation

---

lib/shoulda/matchers/active_model/validate_exclusion_of_matcher.rb

Hello :)
I was reading the example and found an error with the names of the attributes being tested.
Greetings!

fix example with wrong attribute name

---

CHANGELOG.md

I intend to work on this https://github.com/thoughtbot/shoulda-matchers/issues/1433 before releasing a new version.

[skip ci] Bring CHANGELOG up to date

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

Bump version to 5.3.0

---

Appraisals

Wow, I completely forgot to ask @HeitorMC to update the Appraisals file in this PR: https://github.com/thoughtbot/shoulda-matchers/pull/1548
My bad

Remove rails_6_0 in Appraisals

---

LICENSE
README.md

Hi, @mcmire, I hope you're doing great.
What are your thoughts on [ 'Remove Copyright Years'](https://github.com/rails/rails/pull/47467)? To me, it makes sense.

[ci skip] Remove Copyright years

---

CODEOWNERS
README.md

Hello everyone, as you are probably all too aware, I have not been very active as a maintainer over the past few years. The reality is that in my day job, I don't work with Ruby or Rails at all, and outside of work, my time is spent less on side projects and more on family and other sorts of commitments. Because of this, I feel like it is high time that I officially step away from this project.
I want to thank thoughtbot for giving me the opportunity to maintain this gem for so many years (I think I started in 2013!). I also want to thank Pedro and Matheus for keeping the candle burning and continuing to merge new changes, and of course those of you who still find this gem useful in your work even now.
If you still need me for any reason, you can always ping me on Twitter or Mastodon …

Move Elliot to alumni

---

.github/ISSUE_TEMPLATE/bug_report.md

fix: REPRODUCTION_SCRIPT link returning 404

---

CHANGELOG.md
CONTRIBUTING.md
MAINTAINING.md
README.md
REPRODUCTION_SCRIPT.rb

Fixed typos, corrected indentation, and improved grammar for `README.md`, `MAINTAINING.md`, `CHANGELOG.md`, `CONTRIBUTING.md`, & `REPRODUCTION_SCRIPT.rb`

Documentation Readability Enhancement
