spec/acceptance_spec_helper.rb
spec/support/tests/current_bundle.rb
spec/unit_spec_helper.rb

If you attempt to run tests without specifying an Appraisal, then you
will be going off of the main Gemfile. The Gemfile is not guaranteed to
contain all of the dependencies necessary to run tests, so it is very
likely that you'll get an obscure error somewhere. Instead of letting
this happen, raise a specific error.

Raise an error if no Appraisal is specified

---

.hound_config/ruby.yml
spec/support/unit/helpers/active_record_versions.rb
spec/support/unit/helpers/model_builder.rb
spec/support/unit/helpers/rails_versions.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

* The main problem I had with the old tests is that information that
the reader didn't need to care about was not properly abstracted away.
For instance, a helper method used by almost all tests will always
create a model called Example, and will always use an attribute called
"attr" (on which the validation is present). However, in some tests
the class or attribute is referred to directly. The reader shouldn't
have to care about either of these things, since they are constant --
the tests should be readable enough so that this information is not
necessary to understand the case being tested against.
* Speaking of this helper method, some of the tests used it and some
didn't. Some defined their own helper methods to represent a
particular case (`case_sensitive: true`, `allow_nil`, etc.). …

Rewrite tests for validate_uniqueness_of

---

NEWS.md
lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Fixes #402 and #587.
---
This commit fixes the uniqueness matcher so that when qualified with
`scoped_to` and one of the scopes is a UUID column that happens to end
in an "f", the matcher is able to generate a proper next value during
testing and doesn't error.

Uniqueness: Support UUID columns that end in "f"

---

spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

This may or may not be related to #521 (the OP did not have a scoped uniqueness validation).

Uniqueness: Add missing tests for text columns

---

NEWS.md
lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Fixes #521.
Although the tests already passed before for the simple case, this likely also fixes #607.
---
Switch the order of how the column type is detected so that string comes
last. This fixes a bug where if the scope was a text column but was set
to nil before running the matcher, the matcher would fail.

Uniqueness: Fix when scope set to nil beforehand

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Fixes #616.
---
If you have a model that has a uniqueness validation using
`case_sensitive: false`, and you are testing against but do not qualify
the matcher with `case_insensitive`, then the matcher will pass
unexpectedly. Take this model for instance:
```
class Product < ActiveRecord::Base
validates_uniqueness_of :name, case_sensitive: false
end
```
Currently, the following test passes. With this commit, it will now
(correctly) fail:
```
describe Product do
it { is_expected.to validate_uniqueness_of(:name) }
end
```

Uniqueness: Fix default behavior for case-insensitive models

---

NEWS.md
lib/shoulda/matchers/active_model/allow_value_matcher.rb
lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb
spec/support/unit/helpers/model_builder.rb
spec/unit/shoulda/matchers/active_model/allow_value_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_presence_of_matcher_spec.rb

`allow_value` will now raise a CouldNotSetAttribute error if the
attribute in question cannot be changed from a non-nil value to a nil
value, or vice versa. In other words, these are the exact cases in which
the error will occur:
* If you're testing whether the attribute allows `nil`, but the
attribute detects and ignores nil. (For instance, you have a model
that `has_secure_password`. This will add a #password= method to your
model that is defined in a such a way that you cannot clear the
password by setting it to nil -- nothing happens.)
* If you're testing whether the attribute allows a non-nil value, but
the attribute fails to set that value. (For instance, you have an
ActiveRecord model. If ActiveRecord cannot typecast the value in the
context of the column, then it will do nothing, …

allow_value: Raise error if attr sets value differently

---

spec/support/unit/helpers/class_builder.rb
spec/support/unit/helpers/controller_builder.rb
spec/unit/shoulda/matchers/action_controller/permit_matcher_spec.rb

* Use `permit` directly instead of manually building the matcher
* Some tests were being tested by calling #matches? directly when they
shouldn't have been, and some tests were duplicated
* Rename helper methods that define controllers to express intent better
* Don't make a global class (SimulatedError), keep the class local to
the example group
* Use lambdas for that use `raise_error`

Rewrite the tests for #permit

---

NEWS.md
lib/shoulda/matchers/action_controller/permit_matcher.rb
lib/shoulda/matchers/doublespeak.rb
spec/unit/shoulda/matchers/action_controller/permit_matcher_spec.rb

This fixes #648.
----
Previously we were taking ActionController::Parameters and completely
overriding #require, forcing it to return `self`, i.e, the entire
ActionController::Parameters object. This meant that we broke its
functionality, which is to return a slice of the params hash instead.
The consequence of this is that attempting to call #permit on a slice of
the params hash obtained via #require would not work:
``` ruby
params = ActionController::Parameters.new(
{ "course" => { "foo" => "bar" } }
)
params.require(:course)
params.require(:course).permit(:foo)
```
This commit fixes the permit matcher so that #require is proxied
instead, retaining the existing behavior.
This commit also adds a qualifier, #on, for asserting that your action
places a restriction on a slice of the params …

Permit matcher now supports subparameters

---

source/stylesheets/landing/_index.scss

Unfortunately, Brandon Grotesque doesn't have proper small caps, so it makes the large caps look much heavier than the small caps. I personally think that it looks much better without them.

Remove small caps on section header

---

spec/unit_spec_helper.rb

Today if we run a single file or spec like `callback_matcher_spec.rb` or `callback_matcher_spec.rb:12` the formatter is the default dot.
With this config when we run a single file or spec the formatter is the documentation and when we run the suite the formatter is the default dot.
I think this is good when we are working since we have the documentation output when we are doing the TDD and the regular formatter on running all suite.

Run formatter documentation when running a single file

---

README.md

Linking to `#Configuration`  wasn't scrolling the browser to the appropriate anchor in the README

Fix `#configuration` links in README

---

NEWS.md
lib/shoulda/matchers/active_record/define_enum_for_matcher.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb

If your ActiveRecord model stores its `enum` data in a non-integer
column, ActiveRecord will save the data without error. However, when you
access the attribute on the record after saving, AR will look for the
string to what it expects to be a list of numbers and return `nil`
rather than the mapped value.
This change adds a third criterion to the `define_enum_for` matcher,
verifying that the underlying database column has a `sql_type` of
`"integer"`.

Validate enum column is an integer in `define_enum_for`

---

lib/shoulda/matchers/action_controller/route_params.rb
lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Use ```include?``` to check membership of an array instead of ```in?```.
Fixes #877 
All tests passing in this branch.
```
>> bundle check --gemfile='/Users/oogali/shoulda-matchers/gemfiles/4.0.0.gemfile' || bundle install --gemfile='/Users/oogali/shoulda-matchers/gemfiles/4.0.0.gemfile'
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/oogali/shoulda-matchers/gemfiles/4.0.1.gemfile' || bundle install --gemfile='/Users/oogali/shoulda-matchers/gemfiles/4.0.1.gemfile'
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to …
```

Change in? to include?

---

lib/shoulda/matchers/action_controller/permit_matcher.rb
spec/unit/shoulda/matchers/action_controller/permit_matcher_spec.rb

When the permit matcher is used without `#on`, the controller does not use `params#require`, and the params object gets duplicated, the matcher did not recognize the `#permit` call inside the controller. This happened because the matcher overwrote double registries with the same parameter hash whenever ActionController::Parameters was instantiated. The duplication happens unintentionally when passing the params to a model's method that ends up calling `#assign_attributes`, like `#new`.
This is related to #899.
Here's the part of the call stack that was doing the duplication in Rails:
```
/home/ari/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/hash_with_indifferent_access.rb:190:in `dup'
/home/ari/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/actio …
```

Fix permit matcher for multiple instances of params

---

NEWS.md

Last version that supports Rails 4.0 and 4.1 and Ruby 2.0 and 2.1.

Add deprecation notice to NEWS.md

---

lib/shoulda/matchers/doublespeak/object_double.rb

The `delegate_method` matcher uses Doublespeak internally to do its job.
The delegate object is completely stubbed using an ObjectDouble,
available from Doublespeak, which is shoulda-matchers's own test double
library. ObjectDouble is a class that responds to every
method by implementing `method_missing`.
Say you are using Ruby 2.4 and you are testing a class that uses the
Forwardable module to do some delegation, and you are using
`delegate_method` in your test. When you run your test you will a
warning that looks something like:
Courier#deliver at ~/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method #deliver
Why is this happening? When the code in your class gets exercised,
Forwardable will delegate the delegate method in question to
ObjectDouble, and …

Doublespeak: Define #respond_to_missing? on ObjectDouble

---

spec/support/unit/helpers/active_record_versions.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

For some reason, in Rails 5, the uniqueness validation has stopped
working for array columns. What this means is that if you try to use an
array column for a scope, then the query that the validation performs
blows up because the value in the query for the scope is not an array
but a regular scalar value. This does not seem to be documented
anywhere, so perhaps this never worked to begin with, or it accidentally
worked in Rails 4. Until we solve this mystery, skip the tests that have
to do with array columns.

Rails 5: Skip array-column-related tests for uniqueness matcher

---

lib/shoulda/matchers/action_controller/permit_matcher.rb
lib/shoulda/matchers/rails_shim.rb
spec/support/unit/helpers/action_pack_versions.rb
spec/unit/shoulda/matchers/action_controller/permit_matcher_spec.rb
spec/unit_spec_helper.rb

Rails 5 has deprecated the keywords arguments for #permit. This patch scopes the request params according to the version of Rails.
This patch:
+ fixes #867,
+ supercedes #917 such that tests associated with the changes in this PR pass,
+ supercedes #964 to include suggested changes from that PR,
+ is now based on the `rails5` branch.
Thank you (again) to @freesteph for helpin' out!

Scope parameters according to Rails version

---

lib/shoulda/matchers/active_record/association_matcher.rb

autosave was a 4th-level heading, which is inconsistent with all other qualifiers, which are 5th-level.

Fix heading level for autosave in documentation

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb

The methods in the documentation currently just build the objects and
don't save them to the database which doesn't actually solve the
no pre-existing object error.
Think these were just typos.

Use methods that actually persist objects for uniqueness examples

---

Gemfile.lock

There's a known vulnerability in 0.9.9.
https://nvd.nist.gov/vuln/detail/CVE-2017-17042

Update locked yard to 0.9.12.

---

lib/shoulda/matchers/active_model/allow_value_matcher/attribute_setter.rb
lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_inclusion_of_matcher_spec.rb

The warnings that were quelled are:
- Use `BigDecimal()` over `BigDecimal.new`.
Since https://github.com/ruby/bigdecimal/commit/533737338db915b00dc7168c3602e4b462b23503
- Remove duplicated method `model`.

Make `shoulda-matchers` warning free

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/support/unit/matchers/print_warning_including.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

The uniqueness matcher needs to set the attributes under test (which is
not only the attribute you give to the matcher, but also any scope
attributes as well) to arbitrary values so that it can test the
underlying uniqueness validation logic. To set an attribute correctly,
it needs to check what type of column that attribute is and then
generate a value that matches the column (otherwise unpredictable
results happen). The matcher was doing this for scope attributes, but
not for the main attribute. One of the consequences of this
inconsistency is that when setting a boolean attribute, it was using a
string value, which generates a warning under Rails 4.2.
This commit fixes this so that the main attribute is set the same way as
scope attributes, thereby removing the warning.
---
This fixes …

Fix deprecation warning for uniqueness matcher (Rails 4.2)

---

NEWS.md
lib/shoulda/matchers/action_controller/route_matcher.rb
spec/unit/shoulda/matchers/routing/route_matcher_spec.rb

Add with_port qualifier to the route matcher

---

lib/shoulda/matchers/active_record/define_enum_for_matcher.rb
lib/shoulda/matchers/util.rb
lib/shoulda/matchers/util/word_wrap.rb
spec/support/unit/helpers/active_record_versions.rb
spec/support/unit/helpers/message_helpers.rb
spec/unit/shoulda/matchers/active_model/allow_value_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb
spec/unit_spec_helper.rb

In Rails 5, the `enum` macro received two new options: `_prefix` and
`_suffix`. These options change the names of the methods that are
generated from the given enum values. This commit adds qualifiers to the
`define_enum_for` matcher so that they can be tested.
---
Closes #961.

Add prefix and suffix to define enum for

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

This fixes #1081. As discussed, I first added a failing test that confirms the issue is present, then added the fix and checked that the test passed.

Fix validates_uniqueness_matcher for integer attributes

---

.hound/ruby.yml
README.md

These changes should avoid review errors and add support for newer versions of RubCop.
https://github.com/thoughtbot/shoulda-matchers/pull/1117#pullrequestreview-139161705

Update RuboCop config for Hound

---

lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb

Resolves #747  merge conflicts .
---
After some discussion[1] was decided that these qualifiers do not accept
any parameter.
https://github.com/thoughtbot/shoulda-matchers/pull/722

Keep consistency on allow_blank and allow_nil qualifiers

---

shoulda-matchers.gemspec

The site http://thoughtbot.com/community/ doesn't add much information
about the gem itself.

Updated homepage in gemspec

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_absence_of_matcher_spec.rb

There is not an explicit value set for uuid columns in the
validate_absence_of matcher.  The default string value is used which
will get set to nil instead when the type cast happens.  This causes the
matcher to fail when testing that the model does indeed validate for
absence of that attribute.

Handle uuid columns in validate_absence_of

---

.hound/ruby.yml

Fix `.hound/ruby.yml` syntax causing issues for hound and rubocop.

Fix .hound/ruby.yml syntax

---

NEWS.md
lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
lib/shoulda/matchers/active_model/validate_acceptance_of_matcher.rb
lib/shoulda/matchers/active_model/validate_confirmation_of_matcher.rb
lib/shoulda/matchers/active_model/validate_exclusion_of_matcher.rb
lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
lib/shoulda/matchers/active_model/validate_length_of_matcher.rb
lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb
lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb
lib/shoulda/matchers/active_model/validation_matcher.rb
lib/shoulda/matchers/active_model/validation_matcher/build_description.rb
lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/support/unit/rails_application.rb
spec/support/unit/record_validating_confirmation_builder.rb
spec/unit/shoulda/matchers/active_model/validate_absence_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_acceptance_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_confirmation_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_exclusion_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_inclusion_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_length_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_numericality_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_presence_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb
spec/unit_spec_helper.rb
zeus.json

NOTE: This branch incorporates changes from #1133, #1134, and #1135 so that development is easier and all tests pass. When those PRs are merged I'll rebase the branch.
@guialbuk I know this diff is large. I don't expect you to read the whole thing, but I really just wanted to make sure you were aware of the fix here and whether my explanation made sense.
---
When using a validation matcher in the negative, i.e.:
should_not validate_*(...)
as opposed to:
should validate_*(...)
...it's common to receive the following error:
undefined method `attribute_setter' for nil:NilClass
This happens particularly when using a matcher that makes use of
AllowValueMatcher or DisallowValueMatcher internally (which all of the
validation matchers do).
Whenever you make an assertion by using a matcher in the …

Fix negative versions of validation matchers

---

doc_config/yard/templates/default/fulldoc/html/css/global.css
doc_config/yard/templates/default/fulldoc/html/full_list.erb
doc_config/yard/templates/default/fulldoc/html/js/app.js
doc_config/yard/templates/default/fulldoc/html/setup.rb

The current docsite isn't as usable as it should be: clicking on the nav
links should show a popover when in fact it goes to another page. This
is happening because some of the JavaScript is failing on the docsite
due to some old-school code (we're talking early 2000's DHTML stuff)
which was leftover from YARD's default layout which interacts with
frames. We don't use frames on the docsite so there is no need to have
this code.
Also this commit tweaks the CSS for the class list to remove extra
indentation from the bullet points.

Fix UI issues with generated docs

---

CONTRIBUTING.md
MAINTAINING.md
README.md
bin/setup

I started with adding a section on releases and then I realized that there's a lot of knowledge in my head that I haven't really shared, so I did as much brain-dumping as I could. I know this is a lot of information, take your time in reviewing it. But I at least pointed out where the release instructions are so you can have that info now. There's also some info around generating documentation too that you might find helpful.
---
* Move section on documentation from README to CONTRIBUTING
* Add a setup script that contributors and maintainers can use to set up
a dev environment
[skip ci]

Update contributor docs, add maintainer docs

---

MIT-LICENSE
README.md
lib/shoulda/matchers/version.rb

4.0.0.rc1 release and documentation

---

CONTRIBUTING.md

This instruction existed before the last update to the document.

Add instruction to run all tests in CONTRIBUTING

---

CONTRIBUTING.md

After a [recent change to the CONTRIBUTING document](https://github.com/thoughtbot/shoulda-matchers/pull/1150) I realized we were missing a section on Travis, so this commit adds that, and makes a few tweaks to the other sections.

 Add a section on CI to CONTRIBUTING

---

.travis.yml
NEWS.md
README.md
bin/setup

Official support for Ruby 2.2 ended in June 2018, so we are dropping support for it as well.
Ref: https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

Remove Ruby 2.2 support

---

README.md

Improve the documentation on how to integrate the should matchers with RSpec in non Rails projects.
Currently the docs don't specify that `shoulda-matcher` needs to be required before RSpec configuration block.
That leads to a failure when trying to `bundle exec rspec`
```
Failure/Error: config.include(Shoulda::Matchers::ActiveModel, type: :model)
NameError:
uninitialized constant Shoulda
```
Putting `require 'shoulda-matchers'` fixed the issue in my case.

Improve README on how to integrate with RSpec

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb

The documentation shows a wrong example of uniqueness validation:
```ruby
validates :slug, uniqueness: true, scope: :journal_id
```
The correct syntax is:
```ruby
validates :slug, uniqueness: { scope: :journal_id }
```

Fixes uniqueness validator syntax in documentation

---

lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_inclusion_of_matcher_spec.rb

It seems that this method was returning `self` explicitly until [this change](https://github.com/thoughtbot/shoulda-matchers/commit/97e25692537777cf33ea35ad1d4bd18b7de9a777#diff-3706e19f08c07fb311fbf18e8fce5629), but overwriting the method seems to resolve the failure I've been getting.

ValidateInclusionOfMatcher#allow_nil should return `self`

---

NEWS.md
lib/shoulda/matchers/active_record/association_matcher.rb

`balongs_to.without_validating_presence` was introduced in #1170 and both the documentation and the changelog state that the method is called `without_presence_validation`.  Imho the implemented method name is better, so here is the documentation update, to avoid future confusion

Fix `without_validating_presence` documentation

---

lib/shoulda/matchers/active_record/have_db_index_matcher.rb
spec/support/tests/database_configuration.rb
spec/support/unit/helpers/model_builder.rb
spec/support/unit/rails_application.rb
spec/unit/shoulda/matchers/active_record/have_db_index_matcher_spec.rb

Fix #1051. This PR is WIP. 
Hey @mcmire, lemme know what you think.
I'm thinking to rename `ProductionRecord` to something else, as this naming might cause confusion.

Use model class DB connection in have_db_index matcher

---

.rubocop.yml
lib/shoulda/matchers/active_record/define_enum_for_matcher.rb
spec/support/unit/matchers/match_against.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb

When the enum matcher fails, the message it generates is not as clear as
it could be, particularly around showing the expected enum values versus
the actual ones. This commit expands the failure message to be more
helpful (and ensures that the description of the matcher is kept
compact).
---
Fixes #1178.

 Improve failure message for enum matcher

---

bin/setup

I doubt that any of the dependency installations were working on Linux, either, as the setup code was trying to install things with names like `apt=libpq-dev` instead of `libpq-dev`.

Fix installation of Heroku gem when using Homebrew

---

bin/setup

This is a bit tricky to support, since `chruby` is actually a function, not a command. And the script doesn't interact so well with `set -u`. (Thus the `PREFIX=''` and the `chruby ''`.)
Also, chruby doesn't come with its own Ruby installer. Most people will use `ruby-install` though.

Support for folks using chruby

---

lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb
spec/support/unit/helpers/active_record_versions.rb
spec/support/unit/helpers/rails_versions.rb
spec/unit/shoulda/matchers/active_model/validate_presence_of_matcher_spec.rb

When trying to test validation of presence against a active storage relation, shoulda tries to set the attribute as empty string. This makes the association fail to be set and breaks the test.
I've introduced a block that checks if the field is an active storage relation and only allows `nil` to be set to the object.
Fixes #1223

validate_presence_of(:active_storage_field) throws exception

---

.rubocop.yml
lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb
lib/shoulda/matchers/rails_shim.rb
spec/unit/shoulda/matchers/active_model/validate_presence_of_matcher_spec.rb

When using the presence matcher against an ActiveModel record, check to
ensure that the model is using the Attributes API and has explicitly
declared the attribute to be a string before attempting to set the
attribute to an empty string. Otherwise, the attribute may be getting
treated as an object in some point in the validation process, and
therefore setting it to an empty string would create problems.
---
Fixes #1218.
Fixes #1228.

Fix presence matcher against an AM record

---

lib/shoulda/matchers/active_model/allow_value_matcher.rb

Example in allow_values was wrong. It provides a valid value while using
should_not allow_values, so the test was failling but it was claiming in
documentation that the test will pass

Fix typo in documentation of allow_values

---

lib/shoulda/matchers/active_record/association_matcher.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

Allows `belongs_to` associations with `optional: false`
```ruby
belongs_to :copany, optional: false
```
to be tested with
```ruby
it { should belong_to(:copany).optional(false) }
```
It also adds support for `optional(true)` which is the same as just `optional`.
Fixes #1219

Add `optional(false)` support to `belong_to`

---

CONTRIBUTING.md

Hello, I was following the CONTRIBUTING.md file.
At some point it suggest to run this command:
```bash
bundle exec appraisal 5.2 rspec spec/unit/shoulda/matchers/active_model/validate_inclusion_of_matcher_spec.rb
```
But instead of running the tests, it returned:
```bash
bundler: command not found: 5.2
```
So I tried to see the available list of appraisals by running:
```bash
bundle exec appraisal list
```
And this is what I got:
```bash
rails_4_2
rails_5_0
rails_5_1
rails_5_2
rails_6_0
```
Then I replaced the `5.2` with `rails_5_2` and the command worked.

Fix appraisal command in CONTRIBUTING.md file

---

Appraisals
gemfiles/rails_4_2.gemfile
gemfiles/rails_4_2.gemfile.lock
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_0.gemfile.lock
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_1.gemfile.lock
gemfiles/rails_5_2.gemfile
gemfiles/rails_5_2.gemfile.lock
gemfiles/rails_6_0.gemfile
gemfiles/rails_6_0.gemfile.lock
spec/acceptance/independent_matchers_spec.rb
spec/support/acceptance/helpers/step_helpers.rb

It does not look like minitest-reporters dependency provides any benefit to the test suite. Lets drop it.

Remove minitest reporters

---

lib/shoulda/matchers/active_record/association_matcher.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

Shoulda-matchers failed to validate such association:
```
has_many :children, foreign_key: :ancestor_id, inverse_of: false
```

Accepts association with :inverse_of set to false and non standard foreign key

---

lib/shoulda/matchers/active_model/validate_exclusion_of_matcher.rb

Update comments in validate_exclusion_of_matcher.rb

---

spec/support/unit/helpers/model_builder.rb

Hi, this pull request is a draft for now.
I'm looking for a solution to the issue #1262.
Below are some notes about the problem.
The smallest possible scenario for this error to happen:
```ruby
BUNDLE_GEMFILE=/path/to/shoulda-matchers/gemfiles/rails_X_X.gemfile bundle exec rspec './spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb[1:3:2:8:1:1:1,1:5:2:2:1:2:1]' --seed 7438
```
```bash
Shoulda::Matchers::ActiveRecord::ValidateUniquenessOfMatcher
when the model has a case-insensitive validation
when case_insensitive is specified
it supports ignoring_interference_by_writer
when the writer method for the attribute changes incoming values
and the value change causes a test failure
lists how the value got changed in the failure message
when the model has a scoped …
```

Fix intermittent test failures

---

NEWS.md
README.md
lib/shoulda/matchers/version.rb

* Add `have_rich_text` matcher for `ActionText` ([#1263])
* Use range on `validate_exclusion_of#in_range` documentation ([#1273])
* Fix `missing attribute:: scope 1` intermittent test:  ([#1274])

Release version 4.3.0 

---

lib/shoulda/matchers/active_record/have_secure_token_matcher.rb
spec/unit/shoulda/matchers/active_record/have_secure_token_matcher_spec.rb

Fixes https://github.com/thoughtbot/shoulda-matchers/issues/1277
`has_secure_token` [encourages](https://github.com/rails/rails/blob/a273da7619ac6a2b2f98532a5610238c68ad219b/activerecord/lib/active_record/secure_token.rb#L31) to use an index but does not enforce it.
This PR makes the check `has_expected_db_index?` optional.
The default behavior is not changed.

HaveSecureTokenMatcher: optional argument to ignore db index check

---

lib/shoulda/matchers/util.rb
spec/unit/shoulda/matchers/active_model/allow_value_matcher_spec.rb

@mcmire Thanks for reminding me about #1041 by closing it!
Here's the commit I referenced there, rebased onto the latest master.

Truncate long values in descriptions.  Fixes #1041

---

bin/setup

`bin/setup` seems to have a partial implementation for RedHat based Linux distributions (i.e. those using RPM packages).
This completes what is there and as a side note drops the seemingly unused `heroku` requirement.
* Use `rpm=...` packages with `yum`
* Check for `yum` as a package manager
* Drop requirement on `heroku`
**Please note: I am not using a RedHat based Linux at the moment but have tested this out in a docker image for fedora:31 using rbenv to build ruby 2.6.5.**
Yum seems to be currently available in notable RPM distros:
* Fedora 22+ has adopted `dnf` in favour of `yum` but `yum` still seems to be available there.
* RHEL and CentOS 6 to 8 use `yum`

Fix setup script for RedHat based Linux

---

Gemfile.lock
gemfiles/rails_4_2.gemfile.lock
gemfiles/rails_5_0.gemfile.lock
gemfiles/rails_5_1.gemfile.lock
gemfiles/rails_5_2.gemfile.lock
gemfiles/rails_6_0.gemfile.lock

This includes a fix for CVE-2020-8161.

Update rack to 2.2.2

---

lib/shoulda/matchers/active_record/association_matchers/model_reflection.rb
lib/shoulda/matchers/active_record/association_matchers/model_reflector.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/association_matchers/model_reflection_spec.rb

This is to make the association relation receive the expected parameter
(a AR instance, not its class). fix #952

pass correct object type to association reflection

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb

`ActiveRecord::Validations#_validations` is a private API.
Fortunately, Rails provides an API that does exactly what's needed here, and it's been in Rails since at least 3.0.0, so let's use that instead.
***
I ran into an issue using shoulda-matchers with [schema_validations](https://github.com/SchemaPlus/schema_validations). It overrides the public `ActiveModel::Validations` methods to dynamically add validations based on the database schema. Since shoulda-matchers accesses validations using a private API, it incorrectly causes test failures.

uniqueness: don't use a private Rails API

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
lib/shoulda/matchers/util.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

**PR to fix issue #1114**  
The validation fails but it should pass when the scope has data type `time`. 
Example: model `Schedule` with the following attributes and their data types:
`day_of_week`: `integer`
`start_time`: `time`
```ruby
class Schedule
validates :day_of_week, uniqueness: { scope: :start_time }
end
```
Spec:
```ruby
it { should validate_uniqueness_of(:day_of_week).scoped_to(:start_time) }
Failures:
1) Schedule should require case sensitive unique value for day_of_week scoped to start_time
Failure/Error: it { should validate_uniqueness_of(:day_of_week).scoped_to(:start_time) }
Did not expect errors to include "has already been taken" when day_of_week is set to 0,
got errors:
* "has already been taken" (attribute: day_of_week, value: 0) (with different value of start_time) …
```

Bug fix: uniqueness validation fails with scoped attributes of data type time

---

lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb
lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_numericality_of_matcher_spec.rb

Add support to validate numericality of a field when set :other_than comparison

Add support to numericality: :other_than

---

lib/shoulda/matchers/active_record.rb
lib/shoulda/matchers/active_record/have_attached_matcher.rb
spec/support/unit/helpers/active_record_versions.rb
spec/support/unit/helpers/rails_versions.rb
spec/unit/shoulda/matchers/active_record/have_attached_matcher_spec.rb

I am working on issue #1102 to add matchers for `have_one_attached` and `have_many_attached`. I would like to receive some of your opinions about the structuring of the tests. Since the methods define some ActiveRecord associations, a scope, a callback and two methods. I've tried to cover all of the created methods however I don't want to start testing ActiveStorage itself.

Started on ActiveStorage matchers

---

.travis.yml
Appraisals
gemfiles/rails_6_0.gemfile
gemfiles/rails_6_0.gemfile.lock
spec/support/acceptance/helpers/step_helpers.rb

- Remove webpacker gem from Appraisals for version 6.0.
- Remove nvm installation before running CI tests
- On acceptance tests, generate apps without webpacker
Conditionally include --skip-javascript in rails 6.0

Remove webpacker from CI

---

lib/shoulda/matchers/active_record/association_matcher.rb
lib/shoulda/matchers/active_record/association_matchers/join_table_matcher.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

The fix is simple but required slightly rewriting the tests, as it turns
out the existing tests weren't exercising all of the possible checks
that join_table makes.
---
Fixes #1321.

Fix habtm matcher to support symbols for join_table

---

lib/shoulda/matchers/util/word_wrap.rb

This fixes the following warning:
```
vendor/gems/ruby/2.7.0/gems/shoulda-matchers-4.3.0/lib/shoulda/matchers/util/word_wrap.rb:8: 
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

word_wrap: fix Ruby 2.7 warning

---

lib/shoulda/matchers.rb
lib/shoulda/matchers/action_controller.rb
lib/shoulda/matchers/active_model.rb
lib/shoulda/matchers/active_model/allow_value_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers.rb
lib/shoulda/matchers/active_model/validation_matcher.rb
lib/shoulda/matchers/active_record.rb
lib/shoulda/matchers/active_record/association_matchers.rb
lib/shoulda/matchers/active_record/uniqueness.rb
lib/shoulda/matchers/doublespeak.rb
lib/shoulda/matchers/independent.rb
lib/shoulda/matchers/independent/delegate_method_matcher.rb
lib/shoulda/matchers/integrations.rb
lib/shoulda/matchers/integrations/test_frameworks.rb
lib/shoulda/matchers/util.rb

Hi,
First, thanks for the opportunity to work on this issue: #1317
There still some files being loaded with require, I tried to use autoload but got some errors.
I'll keep digging for a solution.

Use autoloading instead of requiring all files up front

---

README.md

Hi!
I noticed that the Readme was not showing any information about this new matcher: https://github.com/thoughtbot/shoulda-matchers/pull/1194
This PR aims to add a link to this new feature.
[ci skip]

Add have_attached_matcher to the Readme

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

* Add an `ignoring_check_for_db_index` qualifier to the `have_secure_token`
matcher, since `has_secure_token` encourages use of an index but does not
enforce it. ([#1278])
* Add `allow_blank` to `validate_length_of` to match other validation matchers.
([#725], [#1318])
* Add new matcher `have_implicit_order_column` which can be used to test the
`implicit_order_column` setting for ActiveRecord models under Rails 6+.
([#1243])
* Add a new `is_other_than` qualifier to `validate_numericality_of` to be able
to test the numericality validation's `:other_than` option. ([#1282])
* Add a new `have_one_attached` and `have_many_attached` matchers for testing
the new model-level ActiveStorage macros in Rails 6. ([#1102])
[#1278]: https://github.com/thoughtbot/shoulda-matchers/pull/1278
[#725]: …

Release v4.4.0

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

* Revert reorganization around autoloading introduced in 4.4.0 which prevented
matchers from being loaded. ([#1334])
[#1334]: https://github.com/thoughtbot/shoulda-matchers/pulls/1334

Release v4.4.1

---

.yardopts
shoulda-matchers.gemspec
tasks/documentation.rb

Related to #1308 which renamed NEWS.md to CHANGELOG.md

fix(docs): Rename remaining NEWS to CHANGELOG [ci skip]

---

Gemfile
Gemfile.lock
doc_config/yard/setup.rb
gemfiles/rails_4_2.gemfile
gemfiles/rails_4_2.gemfile.lock
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_0.gemfile.lock
gemfiles/rails_5_1.gemfile
gemfiles/rails_5_1.gemfile.lock
gemfiles/rails_5_2.gemfile
gemfiles/rails_5_2.gemfile.lock
gemfiles/rails_6_0.gemfile
gemfiles/rails_6_0.gemfile.lock

fix(docs): Migrate to rouge [ci skip]

---

Gemfile.lock

Closes #1342 where incorrect anchors id links were being generated for TOC against redcarpet generated markdown

fix(docs): Upgrade yard [ci skip]

---

.rubocop.yml
Gemfile
Gemfile.lock
shoulda-matchers.gemspec
tasks/documentation.rb

Hi again 👋🏻 
As discussed in #1353, this PR drops `git` in gemspec, thereby also helping in smooth downstream maintenance (in Debian, Fedora, and so on).
Also adds the `Packaging` extension of RuboCop. More about it can be found on https://docs.rubocop.org/rubocop-packaging.
Closes: #1353 
Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

Drop `git ls-files` in gemspec

---

lib/shoulda/matchers/active_model/have_secure_password_matcher.rb
spec/support/unit/helpers/active_model_versions.rb
spec/unit/shoulda/matchers/active_model/have_secure_password_matcher_spec.rb

Starting with version 6, Rails accepts custom attributes for `has_secure_password` macro.
Without one it defaults to `password`, so everything should still work without breaking for older versions of Rails as well.
Rails pull request for allowing configurable attribute name on `#has_secure_password` - https://github.com/rails/rails/pull/26764

Support custom has_secure_password attributes

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb

Add comment about no support of validate_uniqueness_of(:item).scoped_to(array)

---

spec/acceptance/rails_integration_spec.rb
spec/support/acceptance/helpers/step_helpers.rb

This PR corrects two warnings that I ended up encountering when running acceptance tests with Rails 6:
```bash
DEPRECATION WARNING: Using a dynamic :controller segment in a route is deprecated and will be removed in Rails 6.1. (called from block in <main> at /tmp/shoulda-matchers-acceptance/test-project/config/routes.rb:2)
DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.1. (called from block in <main> at /tmp/shoulda-matchers-acceptance/test-project/config/routes.rb:2)
```
~~There is a problem with this PR: The CI will fail when the version of Rails is 4.2. To make it work it's necessary to update the `before { get :show, params: { id: 1 } }` to `before { get :show, { id: 1 } }`, but doing so the tests on the other versions will …

Fix deprecation warning 

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb

Thank you for the awesome library!
You don't actually have to persist the record to get the validates_uniqueness test to pass. Everyone who copies the current code from here is slowing down their test suite unnecessarily.

Use build  instead of create in validate_uniqueness

---

lib/shoulda/matchers/active_record/have_rich_text_matcher.rb
spec/unit/shoulda/matchers/active_record/have_rich_text_matcher_spec.rb

The name should be HaveRichTextMatcher and not HaveRichText.
Thank you, @KapilSachdev, you made me notice this mistake when you reviewed the #1366. Thank you very much.

Fix HaveRichTextMatcher class name

---

lib/shoulda/matchers/active_record/uniqueness.rb

I find this PR([Move uniqueness validation to ActiveRecord module](https://github.com/VSPPedro/shoulda-matchers/commit/cf76d747eef4e04a787fb43badfaa2d459aa5021)) and it seems that this file was the only one missing the update on the module.

Fix module

---

spec/support/unit/rails_application.rb

... as actiontext is made available on rails 6.0

fix: Run actiontext migrations for rails >= 6

---

.github/workflows/rubocop.yml
.hound.yml
README.md

- Annotations feature provided by lint-action is not working with PRs from fork repos
- pull_request_target feature is also not behaving reliably 
- Remove hound
- Note:Not using `bundler-cache: true` for caching as it uses uses `./vendor/bundle` as bundle path and `rubocop` lint vendor as well. So caching under `../vendor/bundle` using `actions/cache`
- Using `actions/cache@v1` rather `v2` as gems are not getting cached due to unknown reason
Related: #1345, #1371

fix: Remove lint-action github action and add custom RuboCop action

---

lib/shoulda/matchers/active_record/association_matchers/option_verifier.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

Closes #1357
It seems to me that the problem here is that when there is no validate option on the relationship the value being returned by `actual_value_for(name)` is nil instead of true - the default value.
In case you want to check the default value for this macro: [documantation](https://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_many) and [active_record/associations/has_many_association.rb#L56](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/has_many_association.rb#L56).
To avoid this I added a check to validate the value and if it is null the default value will be returned instead, otherwise the code will follow its normal flow. I added some tests just to be sure about the behaviour. What do you think?

fix: actual_value_for(validate) returns false instead of true when there is no validate option

---

lib/shoulda/matchers/active_record/association_matcher.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

Closes #1374
I noticed that for the scenario described on issue #1374 the class_has_foreign_key?(klass) was entering in the first conditional and than running this piece of code:
```
option_verifier.correct_for_string?(
:foreign_key,
options[:foreign_key],
)
```
It seems to me that the problem with this flow is that it just returns false without updating the failure message. What do you think?

fix: with_foreign_key modifier fails with wrong error message

---

bin/setup

Running `.bin/setup` on ruby 2.7.2 was returning:
```ruby
./bin/setup: line 240: required_ruby_version: unbound variable
./bin/setup: line 241: required_ruby_version: unbound variable
```
This PR solves this problem, but please test it locally. Thank you.
PS: If you take a look at the [bin/setup](https://github.com/thoughtbot/shoulda-matchers/blob/master/bin/setup) file, you will notice that in some places the variable name is $REQUIRED_RUBY_VERSION and in others, it is $required_ruby_version.
Which one do you prefer?

Fix 'required_ruby_version: unbound variable'

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_absence_of_matcher_spec.rb

My very first time contributing to this gem. 🤓  I love that the [contributing guide](https://github.com/thoughtbot/shoulda-matchers/blob/master/CONTRIBUTING.md) is well-written! 🎉 
This fixes #1240.
- Made `ValidatingAbsenceOfMatcher#value` check whether column is array
- Added tests on array columns for `ValidateAbsenceOfMatcher`

Fix validate_absence_of failing for array columns

---

lib/shoulda/matchers/active_record/have_db_column_matcher.rb
spec/unit/shoulda/matchers/active_record/have_db_column_matcher_spec.rb

Hi!! This is my first contribuition to `shoulda-matchers`. If you got any feedback for this PR, I'll be very happy to listen.
This PR looks to solve the bug reported here #1281. 
When there is an argument this matcher doesn't expect, it should raise an `ArgumentError`. I created a new protected method `validate_options` to be responsible for this.

fix have_db_column.with_options misspelled options

---

lib/shoulda/matchers/active_record/have_db_column_matcher.rb
spec/unit/shoulda/matchers/active_record/have_db_column_matcher_spec.rb

These were introduced after #1358 was merged. Rather bizarrely, RuboCop didn't run when the PR was opened.

Fix RuboCop offenses

---

CHANGELOG.md

There were many PRs merged.
~I'm not sure if I should add all of them or just those that affect the developer using this gem in some way.~
If you would like to change anything, please, let me know.
EDIT: I'll add all.
[ci skip]

Bring CHANGELOG up to date

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

* Add support for has_secure_password custom attributes. ([#1356])
[#1356]: https://github.com/thoughtbot/shoulda-matchers/pull/1356
* Fix `bundle exec yard doc` replacing pygments.rb with rouge to keep the documentation up to date. ([#1343])
* Fix have_db_column.with_options not raising an error when the user adds an invalid value. ([#1358])
* Fix default value of assossiation_matcher.validate option. It was returning false instead of true. ([#1378])
* Fix validate_absence_of failing for array columns. ([#1383])
[#1340]: https://github.com/thoughtbot/shoulda-matchers/pull/1340
[#1358]: https://github.com/thoughtbot/shoulda-matchers/pull/1358
[#1378]: https://github.com/thoughtbot/shoulda-matchers/pull/1378
[#1383]: https://github.com/thoughtbot/shoulda-matchers/pull/1383
* Replace all …

Release v4.5.0

---

MAINTAINING.md

Update the MAINTAINING document to (hopefully) provide a more
streamlined series of steps for creating and publishing new releases.
[ci skip]

Clarify instructions around issuing releases

---

lib/shoulda/matchers/active_record/association_matcher.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

Account for composite primary key in foreign key

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

* Update `belongs_to` to work with composite primary keys. ([#1396])
[#1396]: https://github.com/thoughtbot/shoulda-matchers/pull/1396

Release v4.5.1

---

lib/shoulda/matchers/rails_shim.rb

Hi,
I'm trying to get rid of all the warnings I have when I launch Rspec on my project. Like this one:
> ruby/gems/2.7.0/gems/shoulda-matchers-4.5.1/lib/shoulda/matchers/rails_shim.rb:68: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
That double splat does fix it.

Handle argument delegation for Ruby 3

---

lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb
spec/acceptance/active_record_integration_spec.rb
spec/support/acceptance/helpers.rb
spec/support/acceptance/helpers/active_record_helpers.rb
spec/support/acceptance/helpers/step_helpers.rb

Closes https://github.com/thoughtbot/shoulda-matchers/pull/1291
> The part you quoted was the next thing I was going to say :) ActiveSupport is loaded whether you're explicitly using it or not (because both ActiveModel and ActiveRecord depend on it), but it's designed to be quasi-modular, so the exact file that provides `.in?` may not be required yet.
> 
> In any case, you've convinced me on the consistency argument. The only thing I'd like to see here is a test that exercises the scenario you're in so that we don't run into this problem again. We already some some high-level tests which set up an app and double-check that certain matchers are able to be used. We have a [scenario](https://github.com/thoughtbot/shoulda-matchers/blob/master/spec/acceptance/multiple_libraries_integration_spec …

Fix exception raised by ActiveSupport Object#in?

---

.github/workflows/ci.yml
.rubocop.yml
README.md
doc_config/yard/templates/default/layout/html/setup.rb
lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb
lib/shoulda/matchers/util/word_wrap.rb
shoulda-matchers.gemspec
spec/support/tests/command_runner.rb
spec/support/unit/matchers/fail_with_message_matcher.rb
spec/support/unit/matchers/match_against.rb
spec/unit/shoulda/matchers/active_model/validate_inclusion_of_matcher_spec.rb

The support of ruby 2.5 will end at the end of March 2021. 
Ref: https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/
I'm just leaving the project one step ahead.
What do you think?

Remove ruby 2.5 support

---

bin/setup

Setup script will now recognize RVM if that's your preferred ruby manager 😄

Add RVM (Ruby Version Manager) to setup

---

spec/support/unit/active_record/create_table.rb
spec/support/unit/helpers/active_record_versions.rb
spec/unit/shoulda/matchers/active_model/validate_absence_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_model/validate_presence_of_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/have_db_index_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/have_secure_token_matcher_spec.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

This PR is a continuation of the `Remove Rails 4.2 support` - https://github.com/thoughtbot/shoulda-matchers/pull/1422.
I'll keep this as a draft meanwhile the other PR is not merged.
I realized that we don't need some active record validations in the tests. The purpose of this PR is to remove conditionals that are no longer needed due to the current version that we support.
What do you think?

Refactor ActiveRecordVersions

---

README.md
lib/shoulda/matchers/action_controller/callback_matcher.rb
spec/unit/shoulda/matchers/action_controller/callback_matcher_spec.rb

They are only tested on a version that we don't support anymore. What do you think about removing them?

Remove use_before_filter, use_after_filter and use_around_filter matchers

---

lib/shoulda/matchers/action_controller/permit_matcher.rb
lib/shoulda/matchers/active_record/association_matcher.rb
lib/shoulda/matchers/active_record/association_matchers/join_table_matcher.rb
lib/shoulda/matchers/active_record/association_matchers/required_matcher.rb
lib/shoulda/matchers/rails_shim.rb
spec/support/acceptance/helpers/rails_migration_helpers.rb
spec/support/unit/helpers/action_pack_versions.rb
spec/support/unit/helpers/rails_versions.rb
spec/support/unit/rails_application.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

This PR is a continuation of the Refactor ActiveRecordVersions- #1423.
~I'll keep this as a draft meanwhile the other PR is not merged.~

Remove unnecessary conditions for rails 5.0

---

lib/shoulda/matchers/active_record/association_matcher.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

I noticed that the association matcher was returning a slightly different message between the tests below:
https://github.com/thoughtbot/shoulda-matchers/blob/9763c17d27221c5d3946b0b297b0c17b8f5644f5/spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb#L1451-L1454
https://github.com/thoughtbot/shoulda-matchers/blob/9763c17d27221c5d3946b0b297b0c17b8f5644f5/spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb#L1436-L1439
Pay attention to the foreign_keys, their types are different. This PR standardized the error message  - in both cases the foreign_keys will be symbols. Besides that, these modifications fix one of the four tests that are failing with Rails 6.1.

Standardize error message of association matcher

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

* Replace `in?`, method from ActiveSupport, with `include?` to prevent exception "undefined method `in?`" on non-Rails app. ([#1405])
[#1405]: https://github.com/thoughtbot/shoulda-matchers/pull/1405
* Add support for Rails 6.1. No new Rails 6.1 features are supported, but only
existing features that broke with the upgrade. ([#1418])
* Add support for RVM (Ruby Version Manager) to setting up local environment. ([#1424])
* Add support for alias in matcher define_enum. ([#1419])
* Add support for Ruby 3.0. ([#1406], [#1427])
[#1406]: https://github.com/thoughtbot/shoulda-matchers/pull/1406
[#1418]: https://github.com/thoughtbot/shoulda-matchers/pull/1418
[#1419]: https://github.com/thoughtbot/shoulda-matchers/pull/1419
[#1424]: https://github.com/thoughtbot/shoulda-matchers/pull/1424 …

Release v5.0.0.rc1

---

lib/shoulda/matchers/active_model/helpers.rb
spec/unit/shoulda/matchers/active_model/disallow_value_matcher_spec.rb

Thank you for providing a nice gem.
In shoulda-matchers@v5.0.0.rc1, still there were deprecated methods for Rails6.1 in a helper method and an unit test, which have been renewed.

renew deprecated methods

---

CHANGELOG.md
README.md
lib/shoulda/matchers/version.rb

* Replace `in?`, method from ActiveSupport, with `include?` to prevent exception "undefined method `in?`" on non-Rails app. ([#1405])
[#1405]: https://github.com/thoughtbot/shoulda-matchers/pull/1405
* Add support for Rails 6.1. No new Rails 6.1 features are supported, but only
existing features that broke with the upgrade. ([#1418])
* Add support for RVM (Ruby Version Manager) to setting up local environment. ([#1424])
* Add support for alias in matcher define_enum. ([#1419])
* Add support for Ruby 3.0. ([#1406], [#1427])
[#1406]: https://github.com/thoughtbot/shoulda-matchers/pull/1406
[#1418]: https://github.com/thoughtbot/shoulda-matchers/pull/1418
[#1419]: https://github.com/thoughtbot/shoulda-matchers/pull/1419
[#1424]: https://github.com/thoughtbot/shoulda-matchers/pull/1424 …

Bump version to 5.0.0

---

lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
spec/acceptance/active_model_integration_spec.rb

**Why?**
For non rails project when we try to implement test for inclusion validation, it throws following error:
```
NoMethodError:
undefined method `many?' for ["video_transcoding"]:Array
Did you mean?  any?
```
Screenshot for same:
**Reason:**
The method 'many?' is defined for Rails's ActiveRecord Relation collection, for plain ruby array it gives error.
I also tried this to verify the same:
In rails console (project where we are using rails)
In IRB 
Test execution:
<pre>
➜  shoulda-matchers git:(fix/error-raised-by-ar-relation-method_many) ✗ bundle exec appraisal rails_6_0 rspec spec/acceptance/active_model_integration_spec.rb
>> BUNDLE_GEMFILE=/Users/nitinsingh/projects/gems/shoulda-matchers/gemfiles/rails_6_0.gemfile bundle exec rspec spec/acceptance/active_model_integration_spec.rb …

Fix the undefined method error for non rails project due to use of many? method.

---

lib/shoulda/matchers/active_record/have_db_column_matcher.rb
spec/unit/shoulda/matchers/active_record/have_db_column_matcher_spec.rb

This pull request adds `:array` option support for `have_db_column` matcher.
Rails starting from 4.0 support array columns for postgresql and other databases.
`shoulda matchers` prior to 4.5.0 just ignored so it was passible to write
`expect(...).to have_db_column(:tags).with_options(array: true)`. Check was not actually performed.
`shoulda-matchers` staring from 4.5.0 caused those specs to fail.

Add array option support for have db column matcher

---

.github/workflows/ci.yml
CONTRIBUTING.md
MAINTAINING.md
shoulda-matchers.gemspec

The `master` branch has been renamed to `main` on version 5.1.0 of the gem, but there are still a few references to `master`:
- On CONTRIBUTING.md and MAINTAINING.md documentation files
- On the changelog URL used by rubygems.org
- On the Github Actions settings file

Update references from master to main

---

CONTRIBUTING.md

- Change links from Travis CI to GitHub Actions
- Add an explanation about first-time contributors needing approval

Update the contributing guide about GitHub Actions

---

bin/setup

With Apple moving to M1, homebrew took the opportunity to change the
install location from /usr/local to /opt/homebrew
So check for /opt/homebrew in addition to /usr/local for a chruby.sh
I considered using `brew --prefix` for this, but I'm not sure we can assume it's present at this point in the script

Update bin/setup to detect chruby installed from homebrew on M1

---

spec/support/acceptance/helpers/command_helpers.rb

Noticed this at the bottom of [this action output](https://github.com/thoughtbot/shoulda-matchers/runs/5012675348?check_suite_focus=true#step:8:338) on https://github.com/Gusto/zensa/pull/762
```
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /home/runner/work/shoulda-matchers/shoulda-matchers/spec/support/acceptance/helpers/command_helpers.rb:26)
```

Switch from deprecated Bundler.with_clean_env to Bundler.with_original_env

---

lib/shoulda/matchers/active_record/define_enum_for_matcher.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb

Rails 6 added the `_scopes: false` option when defining enums. This will
prevent rails from creating class scopes for each of the values.
Previously, shoulda-matchers checked for the presence of singleton
methods as a way to check that the corresponding enum methods have been
defined. In rails 6, if someone were using `_scopes: false` the matcher
will fail.
Instead, we should check on the presence of the instance methods that
are generated: `#{value}!` and `#{value}?` as the default checker for
the enum values generating methods.
We can then check on the scopes/singleton methods generated when using
the new `without_scopes` matcher.

Add `without_scopes` to enum matcher.

---

spec/support/acceptance/helpers/step_helpers.rb
spec/support/unit/rails_application.rb

- Use the Rails --skip-bootsnap option instead of commenting it on boot.rb after project creation
I'm closing #1475 in favor of this PR

Skip bootsnap on the test project creation

---

lib/shoulda/matchers/active_model/qualifiers.rb
lib/shoulda/matchers/active_model/qualifiers/allow_blank.rb
lib/shoulda/matchers/active_model/validate_presence_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_presence_of_matcher_spec.rb

Resolves #1407 
allow_blank qualifier for validate_presence_of is now available.
Usage example:
```rb 
it { is_expected.not_to validate_presence_of(:attribute).allow_blank }
```
Tests were implemented.

feat: implement allow_blank qualifier to validate_presence_of

---

spec/support/acceptance/helpers/step_helpers.rb

I think that `--local` should be always preferred and it is already used on other places. Which also leads me to think that the code abuses `run_command_within_bundle!` for purposes it was not intended to be used and `install_gems` should be used instead. But that does not used the `--binstubs` option OTOH. But that might be the preferred solution anyway. Not sure. I could have try that :thinking:

Using local gems should be enough for testing

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

* Add without_scopes method to enum matcher. ([#1453])
* Add support for Ruby 3.1. ([#1474])
* Add allow_blank method to validate_presence_of matcher. ([#1499])
* Add support for Rails 7.0. No new Rails 7.0 features are supported, but only
existing features that broke with the upgrade. ([#1506])
[#1453]: https://github.com/thoughtbot/shoulda-matchers/pull/1453
[#1474]: https://github.com/thoughtbot/shoulda-matchers/pull/1474
[#1499]: https://github.com/thoughtbot/shoulda-matchers/pull/1499
[#1506]: https://github.com/thoughtbot/shoulda-matchers/pull/1506

Bump version to 5.2.0

---

spec/support/unit/rails_application.rb
spec/unit/shoulda/matchers/active_record/have_attached_matcher_spec.rb

Suggestion: instead of creating the table manually, use the command 'bundle exec rake active_storage: install: migrations'.

Install ActiveStorage migrations

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb

This pull request just fixes a typo that I found while reading the code. Thank you.

Fix typo: arbitary -> arbitrary

---

lib/shoulda/matchers/active_model.rb
lib/shoulda/matchers/active_model/numericality_matchers/comparison_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/range_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/submatchers.rb
lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb
spec/support/unit/helpers/rails_versions.rb
spec/unit/shoulda/matchers/active_model/validate_numericality_of_matcher_spec.rb

Closes: #1493
In Rails 7 was added a new option to validate numericality. You can use `in: range` to specify a range to validate an attribute.
```ruby
class User < ApplicationRecord
validates :age, numericality: { greater_than_or_equal_to: 18, less_than_or_equal_to: 65 }
end
class User < ApplicationRecord
validates :age, numericality: { in: 18..65 }
end
```
In this commit we are adding the support matcher to this new functionality, while also making a refactor on the numericality matchers that use the concept of submatchers.
We've created a new class (`NumericalityMatchers::Submatcher`) that's been used by `NumericalityMatchers::RangeMatcher` and `NumericalityMatchers::ComparisonMatcher`, this new class wil handle shared logic regarding having submatchers that will check if the parent …

Add `in: range` matcher to validate_numericality_of

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_absence_of_matcher_spec.rb

Hello, 
I run into a case where I needed to make sure that an `uuid` column was empty but could not use `validate_absence_of` matcher. 
It tried to set the column with "an arbitrary value" which is not a valid uuid value.
This Pull Requests attempts to fix the situation.

Support :uuid column type for validate_absence_of matcher

---

lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_inclusion_of_matcher_spec.rb

All the credits go to [christhomson](https://github.com/christhomson). I can't thank you enough for pointing me in the right direction.
Close https://github.com/thoughtbot/shoulda-matchers/issues/1433
What do you think, @mcmire?
About the issue: https://github.com/rails/rails/pull/42124. Rails now throws an error when the class doesn't exist. To fix this it was necessary to update 'shoulda-matchers test string' to a class name as you can see in this PR.

fix: confusing error message from validate_inclusion_of matcher

---

README.md

Change GitHub workflow badge route

---

lib/shoulda/matchers/active_record/have_db_index_matcher.rb
spec/unit/shoulda/matchers/active_record/have_db_index_matcher_spec.rb

The `have_db_index` matcher currently matches on the first index that has the matching column names. But when used with the `unique` qualifier that *can* result in the "wrong" index being matched causing the test to fail. 
For example, if a column had multiple indexes.. one unique BTree index, and another non-unique partial or GIN index. Using the `unique` qualifier fail because the non-unique index was identified as the `matched_index`.
It would appear that the order returned by `actual_indexes` will be database specific (say by index name) or possibly pseudo-random??
This change applies a "pre sort" of the indexes prior to finding the matching one if the unique qualifier is specified to give the match the best chance of being the "correct" one.
Note that this does of course complicate …

Improve `have_db_index` to better handle columns with multiple indexes

---

.github/workflows/ci.yml
.rubocop.yml
README.md
shoulda-matchers.gemspec

Removes support for Ruby 2.6 due to EOL.
Referent to #1511

Remove Ruby 2.6 support

---

.github/workflows/ci.yml
.rubocop.yml
README.md
lib/shoulda/matchers/util/word_wrap.rb
shoulda-matchers.gemspec

Removes support for Ruby 2.6 due to [EOL](https://www.ruby-lang.org/en/downloads/branches/).
I also checked that Rails 6.0.x will hit EOL on June 1st, 2023. If you guys want to, I can remove it in this PR, or create a new one :)

Remove Ruby 2.7 support

---

lib/shoulda/matchers/util.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Ran into an exception when upgrading to Rails 7.0.4.2 and a column of type `timestamptz`.
```
Failure/Error:
is_expected.to validate_uniqueness_of(:amount).
scoped_to(:column1, :column2, :column3, :date_time_column).
with_message('must be unique')
NoMethodError:
undefined method `getutc' for nil:NilClass
```
After tracing, 'dummy value' was observed as being sent into this function, when then resulted in `time` being nil:
https://github.com/rails/rails/blob/v7.0.4.2/activerecord/lib/active_record/connection_adapters/postgresql/oid/timestamp_with_time_zone.rb#L122

Add timestamptz to the dummy value case statement

---

lib/shoulda/matchers/active_record/have_db_column_matcher.rb
spec/unit/shoulda/matchers/active_record/have_db_column_matcher_spec.rb

Closes #1432
This commit intends to implement the `of_sql_type` qualifier on the `have_db_column` matcher. The implementation is quite simple and follows the pattern of the `HaveDbColumnMatcher` class.

feat: Implement `of_sql_type` qualifier on `have_db_column` matcher

---

lib/shoulda/matchers/action_controller/permit_matcher.rb
lib/shoulda/matchers/active_model/validate_exclusion_of_matcher.rb
lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
spec/support/unit/model_creation_strategies/active_record.rb

We have been using both the terms "whitelist" and "blacklist" to refer to a list of approved/denied values, but I wanted to point out that our dev community recommends the term "allowlist" and "blocklist" instead.
References:
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/whitelist
https://inclusivenaming.org/word-lists/tier-1/#whitelist-blacklist
https://github.com/thoughtbot/guides/tree/main/terminology

fix: Remove non-inclusive terms

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb
lib/shoulda/matchers/active_model/validate_length_of_matcher.rb
lib/shoulda/matchers/active_model/validation_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_length_of_matcher_spec.rb

First step to close: https://github.com/thoughtbot/shoulda-matchers/issues/1559
Were added two mechanisms to treat `validate_length_of_matcher` related attribute as array. One was through `array_column?` helper(also used on `validate_absence_of_matcher`) based on column type if `array?` helper is defined on model's `columns_hash` and another one with an explicit chain method `as_array` that will force to validate column with arrays values.
Why this way? First one will cover pure `array: true` columns for postgresql, second one could be dynamically used to check, for example, json columns storing arrays and being treated like that. This second approach will leave more freedom when using the validator.
Main validate_length_of_matcher specs were duplicated for the two variants. After all …

Extend AM validate_length_of matcher to support array attributes

---

lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb

This commit intends to refactor the `ValidateNumericalityOfMatcher` class in order to make it inherit from `ValidationMatcher` to continue on that pattern and make it consistent across all validation classes.
In the next PR/commit we'll refactor the ValidateComparisonOfMatcher also to follow that pattern.
The major change in that PR is the way we are creating the AllowValueMatcher when using the `allow_nil` qualifier.

refactor: Make `ValidateNumericalityOfMatcher` inherit from `ValidationMatcher`

---

lib/shoulda/matchers/active_model/validate_comparison_of_matcher.rb
lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb

This PR intends to refactor the `ValidateComparisonOfMatcher` class to make it inherit from `ValidationMatcher` to continue on that pattern and make it consistent across all validation classes.
We are also removing some existing methods in the `ValidationMatcher` class from the `ValidateNumericalityOfMatcher` class.

feat: Make `ValidateComparisonOfMatcher` inherit from `ValidationMatcher`

---

lib/shoulda/matchers/active_model/validate_length_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_length_of_matcher_spec.rb

This commit allows the length matcher to be used on associations. It does this by checking if the attribute is an association, and if so, it uses the associations as the attribute to validate.
This commit also adds tests for the length matcher on associations (has_many and has_many through).
I want to credit @prashantjois for the initial work on this feature #1124. I took his work and expanded on it.
If/When this PR gets merged, it'll close #1007 and #1124.

feat: Allow length validation on associations

---

Gemfile
Gemfile.lock
gemfiles/rails_6_1.gemfile
gemfiles/rails_6_1.gemfile.lock
gemfiles/rails_7_0.gemfile
gemfiles/rails_7_0.gemfile.lock

I tried to run specs on my local, but it didn't work. It seems that ``appraisal` v2.4 has a problem with the latest bundler. So I would like to update to the V2.5.
Ref: https://github.com/thoughtbot/appraisal/issues/210#issuecomment-1562556347

Bump `appraisal` gem

---

lib/shoulda/matchers/rails_shim.rb

This change addresses issue #1553
It is a simple one liner allowing ActiveModel related matchers to run when ActiveRecord is not used.
There are no specs for this change due the fact that stubbing of the constant namespace is neither recommended, nor possible.

fix: Ensure that validation specs work for ActiveModel without ActiveRecord

---

lib/shoulda/matchers/active_record.rb
lib/shoulda/matchers/active_record/normalize_matcher.rb
spec/unit/shoulda/matchers/active_record/normalize_matcher_spec.rb

Rails 7.1 adds `normalizes` API.
- [ActiveRecord::Base::normalizes API.](https://github.com/rails/rails/pull/43945)
- [Docs](https://edgeapi.rubyonrails.org/classes/ActiveRecord/Normalization/ClassMethods.html#method-i-normalizes)
I think would be nice to shoulda-matchers to have a matchers to easily test the new `normalizes` API, similar to `allow_value`/`allow_values` matchers. I'm using on my project and this:
```ruby
it "normalizes email" do
user = User.new(email: " \n myEmail@here.com \n\n")
user.normalize_attribute(:email)
expect(user.email).to eq "myemail@here.com"
end
```
Will become this:
```ruby
it { is_expected.to normalize(:email).from(" \n myEmail@here.com \n\n").to("myemail@here.com") }
```
What do you think about? This PR makes sense? 
Some considerations:
- I'm not sure …

Add `normalize` matcher

---

spec/support/unit/configuration.rb
spec/unit_spec_helper.rb

This commit refactors the way we load unit test helpers. Instead of requiring each file individually, we now have a single file that requires all of them. This makes it easier to add new helpers and ensures that they are loaded in the correct order.

refactor: Enhance unit test helpers loading

---

spec/support/unit/change_value.rb

I'm not entirely sure that this will fix this flaky spec, but my bet is that sometimes an invalid `uuid` was generated using the `next` method, this commit avoids that randomness by always generating a new and valid `uuid`.

fix: Adjust flaky spec on `ValidateAbsenceOfMatcher`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.rubocop.yml
REPRODUCTION_SCRIPT.rb

Adding templates for opening issues. This is to help maintain the gem as the issues will have a pattern and possibly a reproduction script.

chore: Add issue templates

---

CHANGELOG.md

* Drop support for Rails 5.2 and 6.0 as well as Ruby 2.6 and 2.7 they've been end-of-lifed by @dougmrqs and @HeitorMC.
The gem now supports Ruby 3.0+ and Rails 6.1+. ([#1521], [#1522], [#1547], [#1548])
[#1521]: https://github.com/thoughtbot/shoulda-matchers/pull/1521
[#1522]: https://github.com/thoughtbot/shoulda-matchers/pull/1522
[#1547]: https://github.com/thoughtbot/shoulda-matchers/pull/1547
[#1548]: https://github.com/thoughtbot/shoulda-matchers/pull/1548
* Fix validate_uniqueness_of matcher not supporting column of the type timestampz by @callahat. ([#1544])
* Ensure that validation specs work for ActiveModel without ActiveRecord by @stonefield. ([#1580])
[#1544]: https://github.com/thoughtbot/shoulda-matchers/pull/1544
[#1580]: …

[skip ci] Bring CHANGELOG up to date

---

CHANGELOG.md
README.md
lib/shoulda/matchers/version.rb

@VSPPedro the bumping PR is ready. Once we have the changelog I can regenerate the docs, publish to RubyGems and create the new tag on GitHub.

release: Bump version to 6.0.0 [skip ci]

---

CHANGELOG.md
README.md

I'll bump a new release including those changes!

chore: Adjust documentation typos [skip ci]

---

lib/shoulda/matchers/active_model/have_secure_password_matcher.rb
spec/unit/shoulda/matchers/active_model/have_secure_password_matcher_spec.rb

closes #1187 
credits goes to @Kutomore Im just adding missing specs to his solution on a new PR because I cant override PR #1192

adds failure_message_when_negated to have_secure_password_matcher

---

lib/shoulda/matchers/active_model/validate_absence_of_matcher.rb

In https://github.com/thoughtbot/shoulda-matchers/pull/1560, `array_column?` helper was extracted to base `validation_matcher` so this helper definition is no longer required on this matcher.

Removing array_column? helper from validate_absence_of_matcher

---

README.md
lib/shoulda/matchers/active_record.rb
lib/shoulda/matchers/active_record/encrypt_matcher.rb
spec/unit/shoulda/matchers/active_record/encrypt_matcher_spec.rb

Since Rails 7.0, [Active Record supports application-level encryption](https://guides.rubyonrails.org/v7.0/active_record_encryption.html).
So i think it would be nice to have a matcher that help to test  usage of the `encrypts` macro:
```ruby
RSpec.describe Survey, type: :model do
it { should have_encrypt_attribute(:access_code).downcase(true)  }
end
```

add have_encrypt_attribute_matcher to test usage of the encrypts macro

---

lib/shoulda/matchers/active_model/comparison_matcher.rb
lib/shoulda/matchers/active_model/numericality_matchers/submatchers.rb
lib/shoulda/matchers/active_model/validate_comparison_of_matcher.rb
spec/unit/shoulda/matchers/active_model/validate_numericality_of_matcher_spec.rb

This commit adjusts the negative form of the `ValidateNumericalityMatcher` so that is does not use the `does_not_match?` method, but uses the negative result of the `matches?` method. This is easy to understand and requires no special handling for the negative form.
Previously, this matcher on the negative form was always returning `true`, as there were no `does_not_match?` method defined, which caused it to use the `does_not_match?` method from the `ValidationMatcher` parent class, which always returns `true`, this commit fixes that.
Closes: #1601

fix: Adjust negative form of `ValidateNumericalityMatcher`

---

.github/workflows/ci.yml
lib/shoulda/matchers/action_controller/permit_matcher.rb
lib/shoulda/matchers/action_controller/set_session_or_flash_matcher.rb
lib/shoulda/matchers/active_model/allow_value_matcher.rb
lib/shoulda/matchers/active_model/comparison_matcher.rb
lib/shoulda/matchers/active_model/validate_comparison_of_matcher.rb
lib/shoulda/matchers/active_model/validate_numericality_of_matcher.rb
lib/shoulda/matchers/active_model/validation_matcher/build_description.rb
lib/shoulda/matchers/active_record/association_matchers/optional_matcher.rb
lib/shoulda/matchers/active_record/association_matchers/required_matcher.rb
lib/shoulda/matchers/active_record/have_db_index_matcher.rb
lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
lib/shoulda/matchers/independent/delegate_method_matcher.rb
lib/shoulda/matchers/util.rb
spec/support/unit/helpers/controller_builder.rb

fixes #1563 
EDIT:after some more verification I noticed we need more changes in order to make the tests pass with the frozen-string option globally enabled. LMK if you guys think this is a useful contribution to project.

make the library work with globally enabled frozen-string-literals

---

lib/shoulda/matchers/active_record/association_matcher.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

Closes: #1592
Rails 7.1 introduced the query_constraints qualifier that can be passed to the association definition.
For example:
```ruby
class Author < ApplicationRecord
self.primary_key = [:first_name, :last_name]
has_many :books, query_constraints: [:author_first_name, :author_last_name]
end
class Book < ApplicationRecord
belongs_to :author, query_constraints: [:author_first_name, :author_last_name]
end
```
We're adding this qualifier to the association matchers.

feat: Add `query_constraints` modifier to `AssociationMatcher`

---

CHANGELOG.md
lib/shoulda/matchers/version.rb

Releasing the 6.1.0 version of the gem.
* Fix negative form of `validate_numericality` matcher by @matsales28 ([#1603])
[#1603]: https://github.com/thoughtbot/shoulda-matchers/pull/1603
* Add support for negated matcher on have_secure_password matcher by @amalrik ([#1593])
* Add `encrypt` matcher to test usage of the `encrypts` macro by @theforestvn88 ([#1581])
* Add `query_constraints` qualifier on the association matchers by @matsales28 ([#1604])
[#1581]: https://github.com/thoughtbot/shoulda-matchers/pull/1581
[#1593]: https://github.com/thoughtbot/shoulda-matchers/pull/1593
[#1604]: https://github.com/thoughtbot/shoulda-matchers/pull/1604
* Remove `array_column?` helper from `ValidateAbsenceOfMatcher` by @jarenas9539 ([#1562])
* Bump rubocop version to 1.59.0 by @VSPPedro ([#1600])
* …

release: Bump version to 6.1.0

---

lib/shoulda/matchers/active_model/allow_value_matcher.rb
spec/unit/shoulda/matchers/active_model/allow_value_matcher_spec.rb

This PR closes #1460 
Create `against` method in allow_value matcher for when validation is on an attribute other than the attribute being validated.

Create against method in allow_value matcher

---

lib/shoulda/matchers/active_record/uniqueness/model.rb
spec/support/unit/model_creation_strategies/active_record.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Quotin @StefSchenkelaars on #1450:
> The uniqueness validation matcher generates a fake class when the scope name ends on _type. This fake class is a duplicate of the original class. In most cases this is not a problem, however when using single table inheritance (STI), this new fake class is not a subclass of the original class and therefore ActiveRecord will throw an error. See #1245
> 
> These problems are fixed by making the fake class inherrit from the original class. Therefore it closes #1245 and closes #854

Ensure uniqueness validation matcher works with STI

---

lib/shoulda/matchers/active_record/normalize_matcher.rb

A colon was missing from the comment and has been corrected.

[skip ci] fix forgotten colon

---

lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb
lib/shoulda/matchers/util.rb
spec/unit/shoulda/matchers/active_model/validate_inclusion_of_matcher_spec.rb

Currently, the min and max range values are checked with `range.first` and `range.max`, that will fail with `cannot get the first element of beginless range (RangeError)` and `cannot get the maximum of endless range (RangeError)` respectively for beginless/endless ranges.
We can rely on `range.begin` and `range.end` (by correctly checking if `end` should be considered by looking at `exclude_end?`) instead, that will both return `nil` instead of raising for beginless/endless ranges.
Also added the required early returns on minimum/maximum value checks when the begin/end of range is absent and updated the specs with two scenarios for beginless/endless ranges.
Fixes #1614.

Allow beginless and endless ranges in validates_inclusion_of

---

lib/shoulda/matchers/active_model/validate_comparison_of_matcher.rb

This PR fixes the initial example the inline documentation of the validate_comparison_of matcher. In the example, the matcher is using `greater_than(...)` in the tests, but it is actually `is_greater_than(...)`.

fix inline documentation about is_greater_than in validate_comparison_of matcher

---

lib/shoulda/matchers/active_record/association_matcher.rb
lib/shoulda/matchers/active_record/association_matchers/model_reflection.rb
lib/shoulda/matchers/active_record/association_matchers/option_verifier.rb
spec/support/unit/helpers/application_configuration_helpers.rb
spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb

`strict_loading` was added to [Rails 6.1] to prevent lazy loading of associations.
As adding it to an association declaration can have a massive impact on the way the record and its association is treated, it can be useful to ensure in a test suite the presence of this option.
This adds support for adding the `strict_loading` option to an association declaration.
[Rails 6.1]: https://github.com/rails/rails/pull/37400
Co-authored-by: Jose Blanco @laicuRoot <jose.blanco@thoughtbot.com>

Support association strict_loading option

---

lib/shoulda/matchers/integrations/libraries/action_controller.rb
lib/shoulda/matchers/integrations/libraries/routing.rb

This PR sets up two `on_load` hooks to include the `ActionController` and `Routing` matchers modules into `ActionController::TestCase`. They run only when `ActionController::TestCase` is loaded rather than immediately whenever the `integrate_with` method is called.
This change should improve app booting performance by delaying the inclusion of the matchers until they are actually needed.

Lazy load `ActionController` and `Routing` matchers for `ActionController::TestCase`

---

CHANGELOG.md
README.md
lib/shoulda/matchers/active_record/association_matcher.rb
lib/shoulda/matchers/version.rb

Releasing the version 6.2.0 of the gem!
* Allow beginless and endless ranges in validates_inclusion_of by @pjpires ([#1615])
* Ensure uniqueness validation matcher works with STI by @matsales28 ([#1610])
* Add `against` method in allow_value matcher by @EduardoSCosta ([#1543])
* Add support for `strict_loading` option in association matchers by @rhannequin and @laicuRoot ([#1607])
* Add `have_delegated_type` matcher by @matsales28 ([#1606])
* Add support for `foreign_type` qualifier on `AssociationMatcher` by @matsales28 ([#1609])
* Lazy load `ActionController` and `Routing` matchers for `ActionController::TestCase` by @ilianah ([#1613])
* Call dynamic-readme reusable workflow by @stefannibrasil ([#1617])
* Update dependencies by @matsales28 ([#1611])
* Fix inline documentation for …

chore: Bump version to 6.2.0

---

lib/shoulda/matchers/active_record/uniqueness/model.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Instead of just initializing a new class that inherits from the parent class, we are initializing a new class but also overriding some method definitions. That is necessary because the Rails guides recommend that whenever you have a polymorphic association and STI you should override the `..._type` column to use the type name of the base STI class.
https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#module-ActiveRecord::Associations::ClassMethods-label-Polymorphic+Associations
This should fix #1622

fix: Polymorphic + STI uniqueness check

---

lib/shoulda/matchers/active_record/define_enum_for_matcher.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb

On this commit we're adding a new qualifier to the `define_enum_for` matcher called `with_default`. This qualifier is used to test that the enum is defined with a default value. A proc can also be passed, and will be called once each time a new value is needed.
It's nice to note that using Time or Date as the return of Procs as default value can lead to flaky tests, so it's recommended to freeze time or date to avoid this.

feat: Add `default` qualifier to `define_enum_for` matcher

---

lib/shoulda/matchers/active_record/define_enum_for_matcher.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb

On this commit we add a new qualifier to the `define_enum_for` matcher called `validating`. This qualifier is used to test if the enum is being validated or not.
```ruby
class Issue < ActiveRecord::Base
enum status: [:open, :closed], validate: true
end
RSpec.describe Issue, type: :model do
it do
should define_enum_for(:status).
validating
end
end
```

feat: Add validating qualifier to enum matcher

---

lib/shoulda/matchers/doublespeak.rb

Ruby 3.4 will warn when `logger` is required without it being part of the gemspec: https://github.com/ruby/ruby/commit/d7e558e3c48c213d0e8bedca4fb547db55613f7c. In 3.5 it will error.
The usage of a logger was added and removed in #1350

Remove useless `logger` require

---

lib/shoulda/matchers/active_record/define_enum_for_matcher.rb
spec/unit/shoulda/matchers/active_record/define_enum_for_matcher_spec.rb

Add a `without_instance_methods` qualifier to enum matcher.
```ruby
class Issue < ActiveRecord::Base
enum status: [:open, :closed], instance_methods: false
end
RSpec.describe Issue, type: :model do
it do
should define_enum_for(:status).
without_instance_methods
end
end
```

feat: Add without_instance_methods qualifier to enum matcher

---

README.md

These seem swapped with each other?

Fix anchor links in readme usage section

---

README.md

As outlined in my comment in https://github.com/thoughtbot/shoulda-matchers/issues/1645, this adds a section that explains the implementation-based testing style that `shoulda-matchers` promotes over behavior-/outcome-based style for the sake of providing clarity to newcomers to the gem, especially less experienced engineers.
I've added it to the "Usage" section. It seemed appropriate there because this section also addresses the topic of `should` vs. `is_expected.to` which, to me, is a similar stylistic topic where opinions and promoted practices might differ.
I'm absolutely open to feedback and adapting individual phrases as well as adding/removing parts as needed -- just let me know.

docs: add section on testing style that we promote (#1645)

---

lib/shoulda/matchers/independent/delegate_method_matcher.rb
spec/unit/shoulda/matchers/independent/delegate_method_matcher_spec.rb

Allow to specify `delegate_method` using `with_private` - which is described in documentation:
```ruby
class Account
delegate :plan, to: :subscription, private: true
end
describe Account do
it { should delegate_method(:plan).to(:subscription).with_private }
end
class PageTest < Minitest::Test
should delegate_method(:plan).to(:subscription).with_private
end
```

Matcher delegate_method supports 'private: true'

---

spec/support/acceptance/helpers/step_helpers.rb

Rails 7.2 enforces sqlite3 >= 1.4
https://github.com/rails/rails/commit/fd1c635d2f1fd8f348ef9fe8a41fb042a8e43482
Rails 8.0 enforces sqlite3 >= 2.1
https://github.com/rails/rails/commit/7c34062b38aa57cdde17a82dd0b10f30a730f655

Enable sqlite3 2.x+

---

lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb
spec/unit/shoulda/matchers/active_record/validate_uniqueness_of_matcher_spec.rb

Resolves #1635. 
This adds an `.alternatives` option to specify alternatives the uniqueness matcher should use to test with if constraints don't allow for freeform alternatives in the column (such as enumerable columns, STI constrained type columns, etc.)

Optionally specify alternatives for uniqueness

---

lib/shoulda/matchers/active_model/validation_matcher.rb

This was broken by this commit. https://github.com/thoughtbot/shoulda-matchers/commit/a4289e9651f140f3d0d40e3480c0ce26f4341822#diff-3762aac43395307304ac640d275475f4e8512211cdd02bfcca21a1223f130d60R27

Ensure @options is always set in ActiveModel::ValidationMatcher.

---

lib/shoulda/matchers/active_record/have_rich_text_matcher.rb
spec/unit/shoulda/matchers/active_record/have_rich_text_matcher_spec.rb

When rich text attributes are declared by passing `encrypted: true` to `has_rich_text`, the attribute class will be
`ActionText::EncryptedRichText` rather than the `ActionText::RichText` base class.
Extend the existing `have_rich_text` matcher such that it will continue to match, even when rich text attributes are specified with the `encrypted: true` option.
Extends work done in #1263.

feat: Support encrypted ActionText attributes
